# Generated by Django 3.1.3 on 2021-06-12 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filtro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filtro', models.CharField(max_length=200, verbose_name='Filtro')),
                ('recurso', models.CharField(max_length=200, verbose_name='Recurso')),
            ],
        ),
    ]
